# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VeePeeWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VeePeeWeatherApp
  pod 'RxSwift'
  pod 'Moya/RxSwift'
  pod 'RxCocoa'
end
